#!/usr/bin/env python3

import sys
from importlib import machinery, util
from pathlib import Path

import sleepi


path = Path('/usr/share/sleepi3-utils/sleepi3_util.py')

loader = machinery.SourceFileLoader(str(path), str(path))
spec = util.spec_from_file_location(str(path), path, loader=loader)
sleepi3_util = util.module_from_spec(spec)
spec.loader.exec_module(sleepi3_util)


ENVIRONMENT_FILE = '/etc/default/sleepi3'


if __name__ == '__main__':
    env = sleepi3_util.parse_environment(ENVIRONMENT_FILE)
    bus = int(env['I2C_BUS'])
    addr = int(env['I2C_ADDRESS'], 16)
    cli = sleepi3_util.Sleepi3Cli(sleepi.Sleepi3(bus, addr))
    
    if len(sys.argv) < 2:
        cli.help()
        sys.exit(2)

    try:
        cmd = sys.argv[1]
        params = sys.argv[2:]
        if cmd in ('-v', '--version', 'version'):
            cli.version()
        elif cmd in ('-s', '--set', 'set'):
            cli.set(params)
        elif cmd in ('-g', '--get', 'get'):
            cli.get(params)
        else:
            cli.help()
    except Exception as e:
        sys.exit(e)


